Console.WriteLine("Nomes das Cidades Do Litoral Sul  Paulista");
Console.WriteLine("Bertioga");
Thread.Sleep(1000);
Console.WriteLine("Cubatão");
Thread.Sleep(1000);
Console.WriteLine("Guarujá");
Thread.Sleep(1000);
Console.WriteLine("Itanhaém");
Thread.Sleep(1000);
Console.WriteLine("Iguape");
Thread.Sleep(1000);
Console.WriteLine("Mongaguá");
Thread.Sleep(1000);
Console.WriteLine("Ilha Comprida");
Thread.Sleep(1000);
Console.WriteLine("Peruíbe");
Thread.Sleep(1000);
Console.WriteLine("Praia Grande");
Thread.Sleep(1000);
Console.WriteLine("Santos");
Thread.Sleep(1000);
Console.WriteLine("São Vicente");
